### ISSUE TITLE
Ability to save recordings to external drive

### ISSUE THREAD

**Issue by dsabella84** [briis/unifiprotect#109]
Just seeing if this was on your road map of changes to allow for recording the cameras.  I get the following error when attempting to record:

async_handle_record_service

raise HomeAssistantError(f"{camera.entity_id} does not support record service")

homeassistant.exceptions.HomeAssistantError: camera.office does not support record service

I am doing this from the developer tools

**Comment by briis** [comment]
It works fine for me.

If I call the service `camera.record` with the below data, it happily records a video for 30 seconds. 

````
entity_id: camera.camera_kitchen
filename: /media/cam_kitchen.mp4
duration: 30
````

Are you sure HA has write access to the filename you specify? Or am I misunderstanding your question?

**Comment by dsabella84** [comment]
Here is the yaml im running

entity_id: camera.office
filename: 'screenshots/snapshot_{{ entity_id.name }}.mp4'
duration: 30

Log from home assistant:

[homeassistant.components.websocket_api.http.connection.140341061422720] camera.office does not support record service

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service

await hass.services.async_call(

File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call

task.result()

File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service

await handler.func(service_call)

File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service

await self.hass.helpers.service.entity_service_call(

File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 459, in entity_service_call

future.result() # pop exception if have

File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call

await coro

File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 490, in _handle_entity_call

await result

File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 714, in async_handle_record_service

raise HomeAssistantError(f"{camera.entity_id} does not support record service")

homeassistant.exceptions.HomeAssistantError: camera.office does not support record service

**Comment by briis** [comment]
I have a G3 Flex also and just testet it, and it works fine for me with this setup:
Service: `camera.record`
Service data:
````
entity_id: camera.camera_office
filename: '/media/{{ entity_id.name }}.mp4'
duration: 30
````
I assume you can view the stream directly in Home Assistant?
Have you enabled the `stream:` component? Must be added to `configuration.yaml`

**Comment by dsabella84** [comment]
I have not,  I'll give that a go and let you know what happens

**Comment by dsabella84** [comment]
Thanks for the help @briis that solved my problem.  Can I recommend including that as part of the instructions on the readme?

**Comment by briis** [comment]
Glad to hear that did the trick. Good suggestion, I will add a note on the stream component to the README.md.
I will close this now.
