### ISSUE TITLE
Integration does not load when a camera is offline

### ISSUE THREAD

**Issue by b-rockx** [briis/unifiprotect#11]
If a camera is offline the Integration fails to load anything.  

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/unifiprotect/binary_sensor.py", line 38, in async_setup_platform
    for camera in cameradata.cameras:
  File "/config/custom_components/unifiprotect/protectnvr.py", line 43, in cameras
    self._api_camera_list = self._get_camera_list()
  File "/config/custom_components/unifiprotect/protectnvr.py", line 127, in _get_camera_list
    upsince = datetime.datetime.fromtimestamp(int(camera['upSince'])/1000).strftime('%Y-%m-%d %H:%M:%S')
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by b-rockx** [comment]
This was on v 0.0.6
v 0.0.8 works. 

Thank you.
