### ISSUE TITLE
Stream connection failed

### ISSUE THREAD

**Issue by Veldkornet** [briis/unifiprotect#112]
Since updating to HA 0.115, I seem to be getting the errors below in my log. After receiving such an error, my CPU also jumps up by about 25% and stays there until I restart. It might not be related to the integration directly, but I thought I need to start somewhere...

UDMP: 1.8.1 RC3
Protect: 1.14.12-beta4

arch: aarch64
chassis: embedded
dev: false
docker: true
docker_version: 19.03.11
hassio: true
host_os: HassOS 4.13
installation_type: Home Assistant OS
os_name: Linux
os_version: 4.19.127-v8
python_version: 3.8.5
supervisor: 245
timezone: Europe/Amsterdam
version: 0.115.5
virtualenv: false

```
2020-09-29 21:29:09 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream packet without dts detected, skipping...
2020-09-29 21:29:11 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream packet without dts detected, skipping...
2020-09-29 21:29:11 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream: No dts in consecutive packets
2020-09-29 21:29:15 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream connection failed: rtsp://192.168.1.1:7447/xxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input: 'rtsp://192.168.1.1:7447/xxxxxxxxxxxxxxxx'
```

**Comment by briis** [comment]
Hi @Veldkornet 
I have exactly the same setup as you, and I am not getting any errors at all in my log. 

There have been some significant changes done in the `stream` component for V0.115. Have you added `stream:` to you configuration.yaml file? I have it added, and as I said, I don't get any errors.
Are you running HA in Docker or another setup? If not the official docker, maybe there is a python component that needs updating?

What happens when try and play `rtsp://192.168.1.1:7447/xxxxxxxxxxxxxxxx'` through VLC?

**Comment by Veldkornet** [comment]
Hmm, I've added the `stream:` to my config, will see if that helps.

The rtsp works fine via VLC FYI
