### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by Veldkornet** [briis/unifiprotect#120]
I seem to be getting a lot of these errors recently... what’s strange to me though is thy it’s listing my public IP in the rstp stream instead of the local one. Is this expected?

HA 0.116.4
Protect: 1.16.0
UDMP: 1.8.2

```
2020-10-18 10:14:17 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream connection failed: rtsp://pu.bl.ic.IP:7447/xxxxxxxxxxx
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input: 'rtsp://pu.bl.ic.IP:7447/xxxxxxxxxxx'
```

I noticed that after a reboot it went back to the local IP, error persists though.

```
2020-10-18 11:28:35 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream connection failed: rtsp://192.168.1.1:7447/xxxxxxxxxxx
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input: 'rtsp://192.168.1.1:7447/xxxxxxxxxxx'

```

**Comment by briis** [comment]
After 0.115, I had to enable `stream:` in my `configuration.yaml`
Do you have that enabled?

**Comment by Veldkornet** [comment]
I have this enabled yes

**Comment by briis** [comment]
Is it a specific Camera that causes this, or random?

**Comment by briis** [comment]
This is fixed with the 0.6.0 release (IN beta right now) that ensures we always use the NVR Internal address.

**Comment by Veldkornet** [comment]
@briis FYI, I've noticed that the error still occurs "regularly" to a specific camera on the other side of a wireless uplink. So I guess it's expected that the connection may fail from time to time.
What's strange is that I can still open the stream from VLC (since the stream comes from the UDM anyway)... mmm... maybe it has to do with the timing.

**Comment by briis** [comment]
OK. On further development, we will see what can be done to reconnect without throwing an error. The Public IP issue should be solved though.
