### ISSUE TITLE
Setting Doorbell Custom Text failed: 403 - Reason: Forbidden

### ISSUE THREAD

**Issue by papacrown** [briis/unifiprotect#135]
Hi, So I am getting the following error when I try to setup the text. I'm using the G4 Doorbell with a Cloudkey Gen2+. 

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in handle_service
    await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
File "/config/custom_components/unifiprotect/camera.py", line 201, in async_set_doorbell_lcd_message
    await self.upv_object.set_doorbell_custom_text(
File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 675, in set_doorbell_custom_text
    raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Setting Doorbell Custom Text failed: 403 - Reason: Forbidden
```

Do I need to change a setting on my Cloudkey?

**Comment by briis** [comment]
Hi there
The local Cloudkey user must have Administrative rights. 
Does the user you use have this?

**Comment by papacrown** [comment]
Ohhh that did it, it worked now. Thanks!
