### ISSUE TITLE
KeyError: 'server_id' during startup of Unifi Protect

### ISSUE THREAD

**Issue by briis** [briis/unifiprotect#147]
After restart of Home Assistant, some of the entities (Switch, Sensor and binary_sensor) sometimes returns a *KeyError: 'server_id'* like the below. 

```log
2020-11-29 08:03:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up unifiprotect platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/unifiprotect/sensor.py", line 32, in async_setup_entry
sensors.append(UnifiProtectSensor(upv_object, protect_data, camera, sensor))
File "/config/custom_components/unifiprotect/sensor.py", line 45, in __init__
super().__init__(upv_object, protect_data, camera_id, sensor)
File "/config/custom_components/unifiprotect/entity.py", line 23, in __init__
self._server_id = self._camera_data["server_id"]
KeyError: 'server_id'
```

**Comment by briis** [comment]
This is clearly a bug, that we are working on. The quick fix is to 
* go to the Integrations Page
* find Unifi Protect
* click the 3 dots in the bottom right and select *Reload*. 

This should fix the problem without having to restart Home Assistant.

**Comment by bdraco** [comment]
I think we can avoid the issue by switching to use hass.data[DOMAIN][entry.entry_id]["server_info"] since the server is will always be in there.  It's a bit cleaner as well.  I'll work something up after I've had some more sleep

**Comment by briis** [comment]
Perfect. Sleep well
