### ISSUE TITLE
Camera Thumbnail: 401 Unauthorized

### ISSUE THREAD

**Issue by xrolfex** [briis/unifiprotect#174]
Entities load in and you can see the stream if you click on one, but the thumbnails fail to load.

I have a user setup and they are a limited admin with admin to protect as well. This was working and now it seems to have stopped.

```
2021-01-10 18:15:13 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 502, in get
return await self.handle(request, camera)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 519, in handle
image = await camera.async_camera_image()
File "/config/custom_components/unifiprotect/camera.py", line 269, in async_camera_image
last_image = await self.upv_object.get_snapshot_image_direct(
File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 571, in get_snapshot_image_direct
raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Direct Snapshot failed: 401 - Reason: Unauthorized
```

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/1327947/104131716-2f38cd80-5346-11eb-96d5-29311811dd96.png">

**Comment by bdraco** [comment]
Do you have anonymous snapshots turned on by chance?

**Comment by xrolfex** [comment]
I do not, and further more, the g4 doorbell won't allow direct access via ip as it seems either. I never had that turned on before when it would work.

**Comment by briis** [comment]
The above error is exactly what you get when you checked the field 'Use anonymous snapshots...' without having this enabled on each camera.
If you go the Integrations Page, and click Options on Unifi Protect, could please double check that this field is not checked?

**Comment by xrolfex** [comment]
That fixed it. I'm not sure how that got checked. Thanks!
