### ISSUE TITLE
return self._device_data["event_on"]   KeyError: 'event_on'

### ISSUE THREAD

**Issue by sj3fk3** [briis/unifiprotect#181]
2021-01-17 16:02:31 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

Traceback (most recent call last):

  File "/config/custom_components/unifiprotect/data.py", line 47, in async_refresh

    self._async_process_updates(

  File "/config/custom_components/unifiprotect/data.py", line 63, in _async_process_updates

    self.async_signal_device_id_update(device_id)

  File "/config/custom_components/unifiprotect/data.py", line 96, in async_signal_device_id_update

    update_callback()

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state

    self._async_write_ha_state()

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state

    sstate = self.state

  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 158, in state

    return STATE_ON if self.is_on else STATE_OFF

  File "/config/custom_components/unifiprotect/binary_sensor.py", line 92, in is_on

    return self._device_data["event_on"]

KeyError: 'event_on'

**Comment by bdraco** [comment]
Looks like a race condition where it isn't populated yet.  Does it always happen on restart or sometimes?

**Comment by sj3fk3** [comment]
> Looks like a race condition where it isn't populated yet. Does it always happen on restart or sometimes?

That was a extremely fast response ;-) 

Looks like a reboot makes it go away, I've seen it before, but have no clue on how to reproduce, or to get into that state. Maybe it has to do with ha startup order?

**Comment by bdraco** [comment]
It probably has to do with how quickly the web socket connects. If it connects before the bootstrap api response returns I'm the issue likely happens.

**Comment by bdraco** [comment]
Got it to happen with the latest firmware

```
2021-01-21 03:02:28 ERROR (MainThread) [pyunifiprotect.unifi_protect_server] Error processing websocket message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 1014, in _setup_websocket
    self._process_ws_message(msg)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 1074, in _process_ws_message
    self._process_camera_ws_message(action_json, data_json)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 1100, in _process_camera_ws_message
    self.fire_event(camera_id, processed_camera)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 1148, in fire_event
    subscriber({device_id: processed_event})
  File "/config/custom_components/unifiprotect/data.py", line 63, in _async_process_updates
    self.async_signal_device_id_update(device_id)
  File "/config/custom_components/unifiprotect/data.py", line 96, in async_signal_device_id_update
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 158, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/unifiprotect/binary_sensor.py", line 92, in is_on
    return self._device_data["event_on"]
KeyError: 'event_on'
```
```
2021-01-21 03:02:24 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 426, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/unifiprotect/binary_sensor.py", line 105, in icon
    if self._device_data["event_ring_on"]:
KeyError: 'event_ring_on'
2021-01-21 03:02:24 ERROR (MainThread) [custom_components.smartir] An error occurred while checking for updates.
2021-01-21 03:02:24 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up unifiprotect platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 426, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/unifiprotect/binary_sensor.py", line 105, in icon
    if self._device_data["event_ring_on"]:
KeyError: 'event_ring_on'

```

**Comment by bdraco** [comment]
@sj3fk3 Can you try the code in https://github.com/briis/unifiprotect/pull/183

**Comment by bdraco** [comment]
Actually I found another issue, but I'm out of time for today.  I'll circle back when I have a fix.
