### ISSUE TITLE
Works fine for 2-3 days, then dies

### ISSUE THREAD

**Issue by avwuff** [briis/unifiprotect#182]
First of all, thank you very much for making this component -- it is awesome.  I use it mainly to get motion alerts from my doorbell, and to have my doorbell press broadcast to all my Nest Hub speakers.

The plugin works great for a few days, and then just dies.  I'm not experienced enough with Home Assistant to know how to determine what is going wrong -- what debug logs or other debugging steps can I do to help solve this issue?

Thanks for your time!

**Comment by briis** [comment]
When it stops working go to "Settings" and then "Logs" and see if anything is recorded here.
When it dies, also try and go to the UniFi Protect App or Web, and see if you get any disconnects or other errors in the Activity page (The bell on the left).
My guess is that it is somehow network related, without being able to be more specific with the information we have.

**Comment by avwuff** [comment]
Thanks, I've reinstalled it now to get it working again, lets see if it keeps working!

**Comment by avwuff** [comment]
Just wanted to update, it's been working fine for 4 days now -- if it stops working again and the reason isn't clear in the logs, I'll update with a new issue.  Thanks!!

**Comment by emkookmer** [comment]
Hi,

I have a similar problem, also IHMO this also related to issue #255

It indeed looks like a network related issue, since my unifi intergration also lost connection to the controller, but that one restarts after 5 minutes (last 2 line). 

> 2021-07-17 01:22:46 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [139983948566096] Connection closed by client
2021-07-17 01:22:46 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [139984046211616] Connection closed by client
2021-07-17 01:22:46 ERROR (MainThread) [custom_components.unifiprotect.data] Error while updating
Traceback (most recent call last):
File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
await self._protectserver.update(
File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 144, in update
updates = await self._get_events(lookback=10)
File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 419, in _get_events
raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Fetching Eventlog failed: 504 - Reason: Gateway Time-out
2021-07-17 01:22:46 WARNING (MainThread) [homeassistant.components.unifi] Lost connection to UniFi controller
2021-07-17 00:27:38 INFO (MainThread) [homeassistant.components.unifi] Will try to reconnect to UniFi controller

**Comment by briis** [comment]
I am sorry, but I cannot reproduce this. I can shutdown my UDMP, and then the integration stops working obviously, but when the UDMP comes back up, it resumes also in HA.
