### ISSUE TITLE
Connect call failed on UDMP FW 1.9.0-10

### ISSUE THREAD

**Issue by briis** [briis/unifiprotect#192]
After updating UDMP to v1.9.0.-10, the below errors are stating to show up. The Integration still works fine when HA is finished starting, but the below error shows up many times in the log. Will try to downgrade 10 1.18 to see if it goes away.

```
Logger: custom_components.unifiprotect.data
Source: custom_components/unifiprotect/data.py:48 
Integration: Unifi Protect (documentation, issues) 
First occurred: 12.34.34 (1 occurrences) 
Last logged: 12.34.34

Error while updating
Traceback (most recent call last):
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 120, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 303, in _get_device_list
    raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Fetching Camera List failed: 500 - Reason: Internal Server Error

```

```
Logger: homeassistant
Source: custom_components/unifiprotect/data.py:48 
First occurred: 12.34.34 (6 occurrences) 
Last logged: 12.34.34

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.1', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 120, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 297, in _get_device_list
    response = await self.req.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.1:443 ssl:False [Connect call failed ('192.168.1.1', 443)]

```

**Comment by briis** [comment]
I removed the Integration and re-added it, and that seems to fix the problem. I get no more errors, and still running 1.9.0-10.

**Comment by briis** [comment]
The beta for the UDMP was really bad, so don't upgrade to it. We will not fix this issue as it might just be the crappy beta, that was causing it. When 1.9 comes out, let us see if this issue resurface
