### ISSUE TITLE
Fix aspect ratio of G4 Doorbell

### ISSUE THREAD

**Issue by jeroenvandisseldorp** [briis/unifiprotect#235]
Currently the integration assumes an aspect ratio of 1.77 for Doorbells similar to other cameras. This compresses the Doorbell's images vertically, since doorbells streams have an aspect ratios of 1.33. Please fix so that Doorbells use 1.33 aspect ratios.

**Comment by briis** [comment]
Hi Jeroen,
I believe I have a fix. To test it out, could you modify the `manifest.json` file in the unifiprotect directory and change this line:

```json
"requirements": [
    "pyunifiprotect==0.30.16"
  ],
```
to this:
```json
"requirements": [
    "pyunifiprotect==0.30.17"
  ],
```
Then restart Home Assistant, and let me know if this works.

**Comment by jeroenvandisseldorp** [comment]
I'm getting errors in the HA log:

2021-05-21 16:15:35 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry gateway for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 94, in async_setup_entry
    await protect_data.async_setup()
  File "/config/custom_components/unifiprotect/data.py", line 32, in async_setup
    await self.async_refresh()
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 123, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 314, in _get_device_list
    self._process_cameras_json(json_response, server_id, include_events)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 335, in _process_cameras_json
    process_camera(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_data.py", line 349, in process_camera
    "image_width": image_width,
UnboundLocalError: local variable 'image_width' referenced before assignment

**Comment by briis** [comment]
I would assume you have disabled RTSP on one or more cameras. Please do the same as above, just change to
 `"pyunifiprotect==0.30.18"` That should get the image_width and height also if RTSP is disabled (Not tested)

**Comment by jeroenvandisseldorp** [comment]
Terrific, yes that worked! Thank you so much for solving!

**Comment by briis** [comment]
Very good. I expect to publish release 0.8.8 tomorrow, that will include this fix.
