### ISSUE TITLE
Error saving thumbnail in automation

### ISSUE THREAD

**Issue by Na3blis** [briis/unifiprotect#245]
I have an automation:
```
alias: Garage Motion Notification
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.motion_garage_g4_bullet
    to: person
    attribute: event_object
condition:
  - condition: template
    value_template: >-
      {{ ( as_timestamp(now()) -
      as_timestamp(state_attr('automation.garage_motion_notification',
      'last_triggered')) |int(0) ) > 60 }}
  - condition: state
    entity_id: input_boolean.unifi_alerts
    state: 'on'
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: unifiprotect.save_thumbnail_image
    data:
      entity_id: camera.garage_g4_bullet
      filename: /config/www/garage-bullet.jpg
  - service: camera.snapshot
    data:
      filename: /config/www/garage-bullet1.jpg
    target:
      entity_id: camera.garage_g4_bullet
  - service: notify.mobile_app_pixel_4
    data:
      message: Person detected at the garage
      data:
        image: https://my-homeassistant.org/local/garage-bullet.jpg
        clickAction: https://my-homeassistant.org/local/garage-bullet1.jpg
        ttl: 0
        priority: high
        channel: Motion
        group: security-garage
mode: single
```
If I trigger the automation manually, it works as expected, you can see the notification here: https://imgur.com/9qPf9Uy
However, when the automation triggers, I get no notification and there's an error in the logs:
```
Logger: homeassistant.components.automation.garage_motion_notification
Source: custom_components/unifiprotect/camera.py:237
Integration: Automation (documentation, issues)
First occurred: 3:48:03 PM (2 occurrences)
Last logged: 3:48:03 PM

Garage Motion Notification: Error executing script. Unexpected error for call_service at pos 2: Thumbnail Request failed: 404 - Reason: Not Found
While executing automation automation.garage_motion_notification
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 666, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/unifiprotect/camera.py", line 237, in async_save_thumbnail
    image = await self.upv_object.get_thumbnail(self._device_id, image_width)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 507, in get_thumbnail
    raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Thumbnail Request failed: 404 - Reason: Not Found
```

**Comment by briis** [comment]
The reason for this is most likely that the thumbnail is not done yet when you run it in an automation. The thumbnail only gets created once the recording is stored. I recommend you replace `service: unifiprotect.save_thumbnail_image` with the `camera.snapshot` service. This should always work and takes a more timely picture.

**Comment by Na3blis** [comment]
Ah, ok, that makes sense. I do like the zoomed in picture of the person better, but seems like that isn't really feasible, since based on what I'm seeing it can last anywhere from 10 seconds to a minute or so. Back to the camera.snapshot then, thanks!
