### ISSUE TITLE
Unable to perform snapshot via unifi-udm-api-proxy

### ISSUE THREAD

**Issue by johntdyer** [briis/unifiprotect#26]
So when I try to run an snapshot I get the following error

```log
2020-02-16 19:26:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140076468150416] Request failed: 404 - Reason: Not Found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 384, in _handle_service_platform_call
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 640, in async_handle_snapshot_service
    image = await camera.async_camera_image()
  File "/config/custom_components/unifiprotect/camera.py", line 165, in async_camera_image
    last_image = self.upv_object.get_snapshot_image(self._camera_id)
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 281, in get_snapshot_image
    access_key = self._get_api_access_key()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 108, in _get_api_access_key
    "Request failed: %s - Reason: %s" % (response.status_code, response.reason)
custom_components.unifiprotect.unifi_protect_server.NvrError: Request failed: 404 - Reason: Not Found

```

I am able to run a POST manually via the [unifi-udm-api-proxy](https://github.com/Silvenga/unifi-udm-api-proxy) using CURL and it works just fine so it seems to be something in how the request is being made via the unifiprotect integration.  I am running 0.105.4 and the lastest version of the plugin...

**Comment by Veldkornet** [comment]
I get a different error with the snapshots:
```
2020-02-24 20:39:35 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 485, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 502, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/unifiprotect/camera.py", line 165, in async_camera_image
    last_image = self.upv_object.get_snapshot_image(self._camera_id)
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 270, in get_snapshot_image
    access_key = self._get_api_access_key()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 97, in _get_api_access_key
    "Request failed: %s - Reason: %s" % (response.status, response.reason)
AttributeError: 'Response' object has no attribute 'status'
```

**Comment by mkgreco** [comment]
I'm also getting`AttributeError: 'Response' object has no attribute 'status'` even though the devices are showing up correctly

**Comment by Veldkornet** [comment]
@mkgreco check https://github.com/Silvenga/unifi-udm-api-proxy/issues/5

**Comment by briis** [comment]
This has been solved in another discussion.
