### ISSUE TITLE
Websocket connection not active error in logs

### ISSUE THREAD

**Issue by copart** [briis/unifiprotect#297]
HASS Version | core-2021.9.3 (in docker)
HACS: 1.15.2
UniFi Protect Integration: 0.9.0

[pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling

**Comment by gokou340** [comment]
I'm also getting the same thing. What version of Protect are you on? I am on 1.19.1 Beta 4

**Comment by briis** [comment]
Hi,
This is not an issue with this integration as far as we can see. It is most likely related to a general network issue. Reloading the UniFi Protect will normally fix the issue, should it occur.
The logging of this, has only just been implemented in the latest release, so it might have been there earlier, just without the log entry. We are looking at not posting the error, unless it continues to occur.

**Comment by copart** [comment]
Protect version 1.19.0 

Anyway to confirm what IP address the integration is using to access the server? Hoping its local and not Internet IP.

**Comment by briis** [comment]
Not sure I understand the question. The Integration uses the IP Address you key in the Config Dialog when setting it up, and that would most often be a local IP address.

**Comment by Veldkornet** [comment]
I had a look at my HomeAssistant log today only to find 50,000+ lines of this
```
2021-09-22 14:33:05 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:07 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:09 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:11 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:13 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:15 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:17 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:19 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
2021-09-22 14:33:21 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling
```

I currently have [UniFi Protect 1.19.2](https://community.ui.com/releases/UniFi-Protect-Application-1-19-2/f96c787a-2b1b-4e3e-af06-bafaac61e3e2).
Reloading the integration does seem to fix the issue.

**Comment by faefangirl** [comment]
Reloaded the integration, then restarted the protect app on my UDM-Pro. Still get this issue:
[31m2021-09-23 14:00:43 ERROR (MainThread) [custom_components.unifiprotect.data] Error while updating

Traceback (most recent call last):
File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
await self._protectserver.update(
File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 409, in update
updates = await self._get_events(lookback=10)
File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 552, in _get_events
data = await self.api_request("events", params=params)
File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 199, in api_request
raise NvrError(msg % (url, response.status, response.reason))
pyunifiprotect.unifi_protect_server.NvrError: Request failed: /proxy/protect/api/events - Status: 500 - Reason: Internal Server Error[0m

[33m2021-09-23 14:00:45 WARNING (MainThread) [pyunifiprotect.unifi_protect_server] Unifi OS: Websocket connection not active, failing back to polling[0m

**Comment by briis** [comment]
@faefangirl In general the above relates to a more generic Network Issue between HA and your UDMP. Error 500 is a kind of 'Catch All' error when the server cannot find a more specific error code.

Are you getting anything setup in HA and are you seeing any events coming in?

**Comment by briis** [comment]
As stated earlier, the cause of these errors can be many things, and is most often a network issue. We have tried to be more specific on the reason for the errors with the 0.9.1 release, so that it could be easier to debug. This release is now in Beta 1, and you can pull it through HACS, if you allow pre-releases.

**Comment by gulli1986** [comment]
I got the exact same issue after updating to unifi protect 1.19.2:

```
Logger: pyunifiprotect.unifi_protect_server
Source: /usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py:406
First occurred: 5:59:11 PM (29 occurrences)
Last logged: 6:00:09 PM

Unifi OS: Websocket connection not active, failing back to polling
```

Will that be solved in the 0.9.1 release?

**Comment by briis** [comment]
The thing is that the above log entry is not by itself an error, it is more a symptom description. It will occur if there are network glitches, which are not directly related to this Integration, but affects the integration by losing the Websocket connection.
Personally I have never seen this error on any of the 3 instances where I have the Integration running.

0.9.1 will improve the details of errors being logged helping to pin-point what is failing, and the above log will only occur if you have `debug` enabled for this integration. So in that sense you might not see it anymore in your logs, but I would still recommend to look at your network configuration as there might be a stability issue here.

**Comment by AngellusMortis** [comment]
There has been no activity on this one since @briis last asked if it was still happening. Closing for now.

0.11 should improve connection issues even more. Feel free to reopen if you keep having the issue. The log should now _only_ appear when you actually have trouble connecting to UFP at an unexpected time.
