### ISSUE TITLE
No entities added for cameraas

### ISSUE THREAD

**Issue by gokou340** [briis/unifiprotect#343]
### Home Assistant Version?

2021.9.6

### UniFi Protect Version?

1.20.0-Beta10

### UniFi Protect HA Integration version?

0.10.0-Beta5.1

### What happened?

At first my doorbell was not triggering the "onpress" event. So in troubleshooting, I removed the plugin and readded and then reconfigured, but now the only entities that show are the cameras themselves. I don't have any switches or other entities.

**Comment by gokou340** [comment]
Possibly relevant logs:


Logger: homeassistant.config_entries
Source: custom_components/unifiprotect/sensor.py:49
Integration: Unifi Protect (documentation, issues)
First occurred: 2:19:26 PM (1 occurrences)
Last logged: 2:19:26 PM

Error setting up entry CVR for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 121, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 335, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 524, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 529, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/unifiprotect/sensor.py", line 49, in <module>
    UnifiProtectSensorEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'entity_category'

**Comment by AngellusMortis** [comment]
You likely need to upgrade to 2021.11

**Comment by gokou340** [comment]
That fixed it. Thanks. I didn't want to update until posting, just incase the update would cause more issues.

What was the reason for needing an update out of curiosity.

**Comment by AngellusMortis** [comment]
https://www.home-assistant.io/blog/2021/11/03/release-202111/#entity-categorization
