### ISSUE TITLE
ViewPort Unable to load views

### ISSUE THREAD

**Issue by ChrisRomp** [briis/unifiprotect#362]
### Home Assistant Version?

2021.11.5

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

0.10.0

### What happened?

It doesn't seem to be able to load the select for the views for the ViewPort device.  Error below.

I suspect this may be a permissions issue, perhaps? What permissions does the user need in Protect?

### Relevant log output

```shell
2021-11-28 20:23:02 ERROR (MainThread) [homeassistant.components.select] Error adding entities for domain select with platform unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/unifiprotect/select.py", line 231, in current_option
    return self._unifi_to_hass_options[unifi_value]
KeyError: '61944a7f03a7a303e7033665'
2021-11-28 20:23:02 ERROR (MainThread) [homeassistant.components.select] Error while setting up unifiprotect platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 93, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/unifiprotect/select.py", line 231, in current_option
    return self._unifi_to_hass_options[unifi_value]
KeyError: '[redacted]'
```

**Comment by ChrisRomp** [comment]
Cameras and camera-specific settings (e.g. privacy mode, IR, LED light, etc.) all work fine.

**Comment by AngellusMortis** [comment]
Is your user that you are using to authenticate with an "Administrator" for UniFi Protect? The default View Only role does not have the ability to see any live views except the ones that account makes.

**Comment by ChrisRomp** [comment]
Not the admin user. I use another user for services. Can you define which permissions are required?

Additional datapoint: The `key error` from the log I redacted because I didn't know what that is, but looking at the device IDs for my Protect cameras, etc., they're all in a similar format, but it's most similar to the ViewPort device.

The Key Error here is like `61944aXXXXXXXXXXXXXXX665` and my ViewPort is `61944bXXXXXXXXXXXXXXX67d`.

**Comment by ChrisRomp** [comment]
Cameras all start with `6052c` and the UNVR starts with `6052a`.

**Comment by ChrisRomp** [comment]
I've made the user an admin with view/edit access to all devices, then restarted HA.  I'm still getting the same error with the `keyerror` of an unknown device.

**Comment by ChrisRomp** [comment]
Aha! The mystery ID is for the live view. I guess `61944b` is the prefix for live views. I set one up under that user and assigned it to the Viewport. The views show up in the select. I'll just share the view with my regular admin user as well.

The other error is related to the doorbell message, it seems. I ought to be able to figure it out as well.
