### ISSUE TITLE
Failed to set up integration

### ISSUE THREAD

**Issue by Sabbath92** [briis/unifiprotect#375]
### Home Assistant Version?

2021.11.5

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

v0.11.0-beta.1

### What happened?

Integration:  Failed to set up. 

Remove integration, restarted HA, added integration back.  Same result. 

### Relevant log output

```shell
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/unifiprotect/data.py:78
Integration: Unifi Protect (documentation, issues)
First occurred: 7:30:53 AM (1 occurrences)
Last logged: 7:30:53 AM

Error setting up entry UNVR-XXXX for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 210, in async_setup_entry
    await protect_data.async_setup()
  File "/config/custom_components/unifiprotect/data.py", line 63, in async_setup
    await self.async_refresh()
  File "/config/custom_components/unifiprotect/data.py", line 78, in async_refresh
    self._async_process_updates(await self._protect.update(force=force))
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 556, in update
    self._bootstrap = await self.get_bootstrap()
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 693, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 100, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 100, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 332, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 277, in _clean_protect_obj_dict
    items[key] = cls._clean_protect_obj(value, klass, api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 665, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 595, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 322, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 354, in unifi_dict_to_dict
    data["text"] = cls._fix_text(data["text"], data.get("type"))
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 361, in _fix_text
    text_type = cls.type.value
AttributeError: type object 'LCDMessage' has no attribute 'type'
```

**Comment by AngellusMortis** [comment]
As a workaround, try changing your doorbell message in UFP to something other than the default message.

**Comment by Sabbath92** [comment]
That worked. Thanks.

**Comment by AngellusMortis** [comment]
Nah, normally a default message is return from UFP as an empty object `{}`. Sometimes though, and I have not figured out how to reproduce, it can return as `{text: "WELCOME", reset_at: null}`. So, with no type. That seems like a UFP bug though that I need to account for.
