### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by addyire** [briis/unifiprotect#378]
### Home Assistant Version?

2021.11.5

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

0.10.1

### What happened?

After updating to protect v0.10.1, my home assistant starts but then crashes shortly after.

The last things that gets logged is that its starting a rtsps stream, but the url of the stream does not match any of the rtsps streams in my unifi protect.

### Relevant log output

```shell
2021-12-04 17:25:30 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsps://10.0.0.2:7441/lJrBJyt5nMYFYjWB?enableSrtp
Illegal instruction
```

**Comment by AngellusMortis** [comment]
Can you try upgrading to the [0.11 beta](https://github.com/briis/unifiprotect/releases/tag/v0.11.0-beta.1) and try again?

**Comment by AngellusMortis** [comment]
Also, are you connecting to your UniFi Protect instance over the Internet or through a reverse proxy (like nginx)?

**Comment by addyire** [comment]
Through a local connection. This happens when I try to configure the 0.11 beta version and Home Assistant just says "Config flow could not be loaded"

```
Traceback (most recent call last):
  File "/home/addyire/vhass/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/home/addyire/vhass/lib/python3.8/site-packages/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/addyire/.homeassistant/custom_components/unifiprotect/__init__.py", line 54, in <module>
    from .services import (
  File "/home/addyire/.homeassistant/custom_components/unifiprotect/services.py", line 14, in <module>
    def _async_all_ufp_instances(hass: HomeAssistant) -> list[ProtectApiClient]:
TypeError: 'type' object is not subscriptable```

**Comment by AngellusMortis** [comment]
You running a standalone install of Home Assistant Core (using a virtualenv)? What version of Python are running?

**Comment by addyire** [comment]
Yes Home Assistant Core, using a virtual environment on Python 3.8.3

**Comment by AngellusMortis** [comment]
Can you try installing/upgrading `typing_extensions` into your virutalenv and retrying? HA core uses types directly instead of their `typing` equivalent even though that requires py3.9, but it looks like `typing_extensions` backports that to 3.8.

https://stackoverflow.com/questions/62871524/is-pep-585-unusable-at-runtime-under-python-3-7-and-3-8

**Comment by AngellusMortis** [comment]
Oh, sorry. I was looking at master instead of the 11-beta.1 tag. That is a bit in beta.1 that has already been fixed on master. You can

* Use `master` as your version from HACS instead -- we will probably do a beta2 in the next couple of days.
* Go back to 0.10.1 -- if you do this, I recommend trying to toggle RTSP on/off the affected cameras and try to restart HA _after_ doing that
* Upgrade to py3.9

**Comment by addyire** [comment]
I changed my Home Assistant to use Home Assistant Container and it now works fine now.

Thanks for the recommendation and trying to help me.

**Comment by stephenjamieson** [comment]
Just as an FYI, I'm on Python 3.9 and I have typing_extensions in a virtualenv and it's not working.

**Comment by AngellusMortis** [comment]
Can you please make a separate issue with full versions of everything and a full stacktrace of the issue you are getting?

**Comment by stephenjamieson** [comment]
> 

Scratch that, I'll open it if I can't get to the bottom of it, but it seems I can't stream the rtsps stream with VLC either and it's causing HASS to crash.

**Comment by AngellusMortis** [comment]
Different issue.

**Comment by AngellusMortis** [comment]
Also, you can get VLC to be able to play RTSPS by enabling this: 
![image](https://user-images.githubusercontent.com/490848/146851836-35896139-973f-4154-b58d-886acf076853.png)
