### ISSUE TITLE
Error Setting Up Entry

### ISSUE THREAD

**Issue by greyduk** [briis/unifiprotect#380]
### Home Assistant Version?

2021.9.5

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

0.10.0

### What happened?

Integration won't ever set up, looks like a configuration_url error? 

### Relevant log output

```shell
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/unifiprotect/__init__.py:124
Integration: Unifi Protect (documentation, issues)
First occurred: 11:08:30 AM (1 occurrences)
Last logged: 11:08:30 AM

Error setting up entry ***_UDMPRO for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 108, in async_setup_entry
    await _async_get_or_create_nvr_device_in_registry(hass, entry, nvr_info)
  File "/config/custom_components/unifiprotect/__init__.py", line 124, in _async_get_or_create_nvr_device_in_registry
    device_registry.async_get_or_create(
TypeError: async_get_or_create() got an unexpected keyword argument 'configuration_url'
```

**Comment by AngellusMortis** [comment]
See pinned issue.

**Comment by bdraco** [comment]
https://github.com/briis/unifiprotect/issues/365
