### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by kasper79** [briis/unifiprotect#405]
### Home Assistant Version?

core-2021.12.1

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11-beta.4

### What happened?

Noticing ERROR's in the log, not sure if it's something I've done or configured incorrectly but wanted to share... Integration works as expected and no issues, so that's good :)
I apologize if this is just on mine and something i've done.
Please let me know if I can provide any more info.

### Relevant log output

```shell
Log Details (ERROR)
This error originated from a custom integration.
Logger: pyunifiprotect.api
Source: custom_components/unifiprotect/binary_sensor.py:322
Integration: UniFi Protect (documentation, issues)
First occurred: 8:18:41 AM (290 occurrences)
Last logged: 8:48:01 AM

Exception while running subscription handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 582, in emit_message
    sub(msg)
  File "/config/custom_components/unifiprotect/data.py", line 104, in _async_process_ws_message
    self.async_signal_device_id_update(message.new_obj.id)
  File "/config/custom_components/unifiprotect/data.py", line 171, in async_signal_device_id_update
    update_callback()
  File "/config/custom_components/unifiprotect/binary_sensor.py", line 282, in _async_updated_event
    self._async_fire_events()
  File "/config/custom_components/unifiprotect/binary_sensor.py", line 296, in _async_fire_events
    self._async_fire_motion_event()
  File "/config/custom_components/unifiprotect/binary_sensor.py", line 322, in _async_fire_motion_event
    assert isinstance(self.device, (Camera, Light))
AssertionError
```

**Comment by kasper79** [comment]
That was after a reboot (after upgrading to beta4) before the reboot that message showed up 10546 times.

**Comment by AngellusMortis** [comment]
Ah! You have a UFP-Sense. I will make a PR to clean that error up. And yeah, everything should still be working fine except maybe your binary sensor for motion on the sense.

**Comment by kasper79** [comment]
Ohh yea, I have 2 of them!  Thank you!!
