### ISSUE TITLE
"Failed to set up" after upgrading to 0.11 Beta 4

### ISSUE THREAD

**Issue by deanryan** [briis/unifiprotect#408]
### Home Assistant Version?

2021.12.1

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11 Beta 4

### What happened?

I had 0.10.1 installed and working, but I wanted to use the SmartDetection features, so I installed 0.11 Beta 4 to give it a try.  After upgrading, the Unifi Protect integration "Failed to set up".  Log with stack trace is attached.  I am able to revert to 0.10.1 okay, but I have been unable to determine why the upgrade to 0.11 Beta 4 is failing.  I have also tried other 0.11 Beta versions, but they all seem to fail in the same manner.  I have looked through the other reported issues and did not find any that appear to be related.

### Relevant log output

```shell
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/unifiprotect/data.py:89
Integration: UniFi Protect (documentation, issues)
First occurred: 10:54:31 AM (2 occurrences)
Last logged: 10:58:23 AM

Error setting up entry Cloud Key Plus for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 210, in async_setup_entry
    await data_service.async_setup()
  File "/config/custom_components/unifiprotect/data.py", line 74, in async_setup
    await self.async_refresh()
  File "/config/custom_components/unifiprotect/data.py", line 89, in async_refresh
    self._async_process_updates(await self.api.update(force=force))
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 562, in update
    self._bootstrap = await self.get_bootstrap()
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 699, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 100, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 100, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 332, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 277, in _clean_protect_obj_dict
    items[key] = cls._clean_protect_obj(value, klass, api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 678, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 595, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 322, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 315, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 159, in convert_unifi_data
    value = [convert_unifi_data(v, field) for v in value]
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 159, in <listcomp>
    value = [convert_unifi_data(v, field) for v in value]
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 177, in convert_unifi_data
    value = field.type_(value)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'face' is not a valid SmartDetectObjectType
```

**Comment by AngellusMortis** [comment]
What cameras do you have? I am not aware (at least none of the ones I have) that lets you do smart detections for faces.

**Comment by deanryan** [comment]
Camera G4 Dome.  It doesn't do face detection that I am aware of either.  It has the latest released firmware installed (4.46.18).  The "face" value was confusing to me as well.

**Comment by AngellusMortis** [comment]
In the Web UI, do you have anything different for your settings then this? 

![image](https://user-images.githubusercontent.com/490848/146224478-330cd9a9-a624-4c84-9ff6-20b0d714e41c.png)

**Comment by deanryan** [comment]
Yes:
- Recording Mode: Detections
- Seconds to record before: 2s
- Seconds to record after: 2s

Everything else matches.

By the way...not sure if this is useful information, but this is a brand-new Unifi Protect installation.  I only have the one camera (Ubiquiti or otherwise), and I've never had any other cameras integrated with my HAS system.

**Comment by AngellusMortis** [comment]
It must be a new unreleased feature then that is not available yet in the UI. It is annoying though that it is only for the G4 Dome, which does not seem to have anything special about it. I will add the face smart detect type so you can get everything working, but I would really love to know what is going on with it. haha.

**Comment by deanryan** [comment]
I'm intrigued as well.  Thanks for you help and great work!

**Comment by AngellusMortis** [comment]
I may or may not have already bought a G4 Dome since they are in stock to play around with it. 😂

**Comment by AngellusMortis** [comment]
beta5 should be there (might need to force a redownload).

**Comment by deanryan** [comment]
Success!  Integration starts up and I'm seeing the expected devices and entities.  Thanks for the quick turn-around!
