### ISSUE TITLE
ValueError: 'unknown' is not a valid VideoMode

### ISSUE THREAD

**Issue by andypm1982** [briis/unifiprotect#423]
### Home Assistant Version?

2021.12.4

### UniFi Protect Version?

1.20

### UniFi Protect HA Integration version?

0.11.1

### What happened?

Fresh Home Assistant install with unifi protect.

Created a local admin account on the unifi protect console. No outstanding updates.

Soon as i enter the required information for the integration like ip address username password etc all appears to be fine but then get an error

ValueError: 'unknown' is not a valid VideoMode

Ive tried resetting the admin password etc along with using my own ubnt cloud login details but can never get past this error.

Thanks.

### Relevant log output

```shell
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/unifiprotect/data.py:89
Integration: UniFi Protect (documentation, issues)
First occurred: 2:05:03 PM (2 occurrences)
Last logged: 2:11:20 PM

Error setting up entry UNVR for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 210, in async_setup_entry
    await data_service.async_setup()
  File "/config/custom_components/unifiprotect/data.py", line 74, in async_setup
    await self.async_refresh()
  File "/config/custom_components/unifiprotect/data.py", line 89, in async_refresh
    self._async_process_updates(await self.api.update(force=force))
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 562, in update
    self._bootstrap = await self.get_bootstrap()
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 699, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 100, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 100, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 332, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 277, in _clean_protect_obj_dict
    items[key] = cls._clean_protect_obj(value, klass, api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 678, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 595, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 315, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 177, in convert_unifi_data
    value = field.type_(value)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'unknown' is not a valid VideoMode
```

**Comment by AngellusMortis** [comment]
This might be related to https://github.com/briis/unifiprotect/issues/420. Do you have any cameras that are unadopted or adopted by another NVR?

**Comment by andypm1982** [comment]
i took your suggestion and re-adopted and removed/re-installed the addon and it made no difference

**Comment by AngellusMortis** [comment]
Well, if you have undopted devices, the current versions might not work at all. If you adopt them, you probably need to restart HA. 

I was mostly just looking for confirmation you had unadopted devices. If you did, I can put out 0.11.2 now and that should fix it. Otherwise, I wanted to troubleshoot you issue before we make another release.

**Comment by andypm1982** [comment]
ill restart HA and try again

**Comment by AngellusMortis** [comment]
I just added `unknown` as a VideoMode for if unadopted entities get through, but they should be _completely_ ignored by HA. At least for now. Going to close this now assuming it is fixed. 

If you are still having troubles though, do not hesitate to re-open or comment back.

**Comment by andypm1982** [comment]
whatever you did worked fine, protect is now working again and i can see my cameras. Many Thanks.
