### ISSUE TITLE
No more connection, Error setting up.

### ISSUE THREAD

**Issue by mupsje** [briis/unifiprotect#426]
Error setting up.

Suddenly I have no more active cams anymore....

please advice

```
2021-12-23 10:11:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Casa Tropical for unifiprotect
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/unifiprotect/__init__.py", line 210, in async_setup_entry
await data_service.async_setup()
File "/config/custom_components/unifiprotect/data.py", line 74, in async_setup
await self.async_refresh()
File "/config/custom_components/unifiprotect/data.py", line 89, in async_refresh
self._async_process_updates(await self.api.update(force=force))
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 567, in update
self._bootstrap = await self.get_bootstrap()
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 704, in get_bootstrap
return Bootstrap.from_unifi_dict(**data, api=self)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 100, in from_unifi_dict
data = cls.unifi_dict_to_dict(data)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 132, in unifi_dict_to_dict
return super().unifi_dict_to_dict(data)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 332, in unifi_dict_to_dict
data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 277, in _clean_protect_obj_dict
items[key] = cls._clean_protect_obj(value, klass, api)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
return klass.unifi_dict_to_dict(data=data)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 680, in unifi_dict_to_dict
return super().unifi_dict_to_dict(data)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 595, in unifi_dict_to_dict
return super().unifi_dict_to_dict(data)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 322, in unifi_dict_to_dict
data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
return klass.unifi_dict_to_dict(data=data)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 325, in unifi_dict_to_dict
return super().unifi_dict_to_dict(data)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 315, in unifi_dict_to_dict
data[key] = convert_unifi_data(data[key], cls.__fields__[key])
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 177, in convert_unifi_data
value = field.type_(value)
File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
raise ve_exc
ValueError: 'motion' is not a valid RecordingMode
```

**Comment by AngellusMortis** [comment]
Please use the provided issue template and make a new issue. Also, please. Make sure you are running Protect 1
20 or newer (see pinned issue: https://github.com/briis/unifiprotect/issues/365).
