### ISSUE TITLE
Crash when camera configured but not running

### ISSUE THREAD

**Issue by jcollas** [briis/unifiprotect#429]
### Home Assistant Version?

2021.12.5

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11.4

### What happened?

I have 2 configured Unifi Protect cameras (G3 Flex).  One is operational, the other is configured, but has a hardware fault and doesn't work.  I think the crash is due to attempting to access the data from the configured but non-working camera.

Obviously, with the crash I can't use the operational camera.

### Relevant log output

```shell
2021-12-26 08:21:10 ERROR (MainThread) [homeassistant.components.camera] Error while setting up unifiprotect platform for camera                        
Traceback (most recent call last):                                                                                                                      
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform                                            
    await asyncio.shield(task)                                                                                                                          
  File "/config/custom_components/unifiprotect/camera.py", line 96, in async_setup_entry                                                                
    for camera, channel, is_default in get_camera_channels(data.api):                                                                                   
  File "/config/custom_components/unifiprotect/camera.py", line 83, in get_camera_channels                                                              
    yield camera, camera.channels[0], True                                                                                                              
IndexError: list index out of range
```

**Comment by AngellusMortis** [comment]
Huh. Somehow the code that protects against that crash was reverted in the 0.11.x branch. I am not completely sure how. As long as you are not using any of the deprecated features of 0.11.x, it should be safe for you to upgrade to the 0.12-beta which is the final version that will be in HA core when it is all finished and merged in.

**Comment by jcollas** [comment]
Yup, the beta works fine.  Thanks!

**Comment by AngellusMortis** [comment]
Thanks for verifying for me. 

I am going to mark using 0.12 beta as the solution then, so I do not need to make more changes to the 0.11.x branch. I do not think many people will have this issue (the hardware failure one, the other cause was for unadopted devices, which that has also been solved separately.
