### ISSUE TITLE
Cannot use DNS host for connection host manually set within camera

### ISSUE THREAD

**Issue by tkk2112** [briis/unifiprotect#431]
### Home Assistant Version?

2021.12.5

### UniFi Protect Version?

1.20.1

### UniFi Protect HA Integration version?

0.11.4

### What happened?

I upgrade both HA and the integration to latest, and then the integration wouldn't load, I didn't carefully check the logs so I don't know what the issues was. I delete the integration and reconfigured it with `se-gw.local` as host, that works fine in the wizard but the integration wont start saying `Failed to set up - Check the logs` the python exception raised is `ipaddress.AddressValueError: Expected 4 octets in 'se-gw.local'` which makes sense since I wront in a dns name instead of an IP address. But when deleting this integration and writing the IP directly its keeps saying `ipaddress.AddressValueError: Expected 4 octets in 'se-gw.local'`. Does it "cache" it or something?

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 210, in async_setup_entry
    await data_service.async_setup()
  File "/config/custom_components/unifiprotect/data.py", line 74, in async_setup
    await self.async_refresh()
  File "/config/custom_components/unifiprotect/data.py", line 90, in async_refresh
    self._async_process_updates(await self.api.update(force=force))
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 568, in update
    self._bootstrap = await self.get_bootstrap()
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 717, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 100, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 132, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 332, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 277, in _clean_protect_obj_dict
    items[key] = cls._clean_protect_obj(value, klass, api)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 261, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 680, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 595, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 315, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 163, in convert_unifi_data
    value = IPv4Address(value)
  File "/usr/local/lib/python3.9/ipaddress.py", line 1307, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/local/lib/python3.9/ipaddress.py", line 1194, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'se-gw.local'
```

**Comment by AngellusMortis** [comment]
What UniFi OS console are you using? 

Can you go to `https://{protect_ip/host}/proxy/protect/api/nvr` and search for `hosts` and give me the value found there?

**Comment by tkk2112** [comment]
> What UniFi OS console are you using?
> 
> Can you go to `https://{protect_ip/host}/proxy/protect/api/nvr` and search for `hosts` and give me the value found there?

```
hosts |  
0 | "10.0.10.1"
1 | "10.0.12.1"
2 | "10.0.13.1"
```

**Comment by AngellusMortis** [comment]
What about the `host` value? Do you see that hostname anywhere under `/proxy/protect/api/bootstrap`?

And you missed responding to what UniFi OS console you were using.

**Comment by tkk2112** [comment]
> What about the `host` value? Do you see that hostname anywhere under `/proxy/protect/api/bootstrap`?
`host | "10.0.10.1"`

> And you missed responding to what UniFi OS console you were using.
Is it this `UniFi OS Version 1.11.0` you asking about?

**Comment by AngellusMortis** [comment]
No, what console is it? Do you have a UDM Pro? A Cloud Key? etc.

**Comment by tkk2112** [comment]
UDM Pro

**Comment by tkk2112** [comment]
> What about the `host` value? Do you see that hostname anywhere under `/proxy/protect/api/bootstrap`?

I have two "offsite" cameras that using se-gw.local as connectingHost, thats the only meantion in that json file

**Comment by AngellusMortis** [comment]
How did you set the connection host on those cameras? As far as I know, UniFi Protect does not let you do that.

**Comment by tkk2112** [comment]
Directly on the cameras webinterface

**Comment by AngellusMortis** [comment]
As a work around for now, if you set that connection host to an IP address instead of a DNS name, it should let it start working for you. I can work on a fix that will let you use the DNS name again.

**Comment by tkk2112** [comment]
> As a work around for now, if you set that connection host to an IP address instead of a DNS name, it should let it start working for you. I can work on a fix that will let you use the DNS name again.

The work around solved it, thanks

**Comment by AngellusMortis** [comment]
As a note, if either of those off-site cameras have speakers, you may have issues using the talkback feature (media player added to HA to let you play audio files/TTS through speaker). HA has to be able to directly connect to the speakers to send the audio to them.

**Comment by AngellusMortis** [comment]
Reopening as the fix is not published yet for the HA integration.

**Comment by AngellusMortis** [comment]
Sorry, Github likes to preempitively close issues when you reference them in PRs. 

I just pushed out 0.12.0-beta4. Please let me know if know if the DNS issues are resolved and/or if you have any other issues.

**Comment by VederJay** [comment]
I've ...

- removed the integration
- removed the repo from HACS
- restarted HASS
- downloaded the repo through HACS and made sure to select the 0.12.0-beta4 version
- restarted HASS
- set up the integration again

And again, after entering the connection data and the credentials, the log shows:
```
Logger: homeassistant.config_entries
Source: .local/lib/python3.9/site-packages/pyunifiprotect/utils.py:167
First occurred: 22:40:21 (1 occurrences)
Last logged: 22:40:21

Error setting up entry UNVR myUNVR for unifiprotect
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 208, in async_setup_entry
    await data_service.async_setup()
  File "/config/custom_components/unifiprotect/data.py", line 75, in async_setup
    await self.async_refresh()
  File "/config/custom_components/unifiprotect/data.py", line 95, in async_refresh
    updates = await self.api.update(force=force)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 575, in update
    self._bootstrap = await self.get_bootstrap()
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 724, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 101, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 132, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 333, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 278, in _clean_protect_obj_dict
    items[key] = cls._clean_protect_obj(value, klass, api)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 262, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 680, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 596, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 316, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
  File "/config/.local/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 167, in convert_unifi_data
    value = field.type_(value)
  File "/usr/lib/python3.9/ipaddress.py", line 1307, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/lib/python3.9/ipaddress.py", line 1194, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'unvr.mydomain.com'
```

**Comment by AngellusMortis** [comment]
Can you go through similar trough similar troubleshooting as the user above did?

i.e. go to `https://{protect_ip}/proxy/protect/api/bootstrap` and then look for references to your hostname and then report back to me which fields they are in. JSONView ([Chrome](https://chrome.google.com/webstore/detail/jsonview/gmegofmjomhknnokphhckolhcffdaihd) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/jsonview/)) is a really great way to make the JSON readable.

**Comment by VederJay** [comment]
Ok, got a 401 initially but that was because I was only logged in through the cloud interface and not locally. 
After smacking myself, I'm finding 3 references for the hostname in the camera settings for the 3 remote camera's. I've left in a local camera of the same type to clearly show the difference, and some details on the unvr. 
```
{
  "cameras": [
    {
      "host": "192.168.1.35",
      "connectionHost": "unvr.mydomain.com",
      "type": "UVC Micro",
      "modelKey": "camera"
    },
    {
      "host": "192.168.1.11",
      "connectionHost": "unvr.mydomain.com",
      "type": "UVC Micro",
      "modelKey": "camera"
    },
    {
      "host": "192.168.1.6",
      "connectionHost": "unvr.mydomain.com",
      "type": "UVC Micro",
      "modelKey": "camera"
    },
    {
      "host": "192.168.0.24",
      "connectionHost": "192.168.0.17",
      "type": "UVC Micro",
      "modelKey": "camera"
    }
  ],
  "nvr": {
    "host": "192.168.0.17",
    "name": "UNVR myUNVR",
    "timezone": "Europe/Brussels",
    "version": "1.20.3",
    "ucoreVersion": "2.3.26",
    "firmwareVersion": "2.3.10",
    "uiVersion": null,
    "hardwarePlatform": "al324",
    "releaseChannel": "release",
    "hosts": [
      "192.168.0.17"
    ],
    "enableBridgeAutoAdoption": true,
    "hostShortname": "UNVR",
    "isHardware": true,
    "isWirelessUplinkEnabled": false,
    "timeFormat": "24h",
    "network": "Ethernet",
    "type": "UNVR4",
    "modelKey": "nvr"
  }
}
```

**Comment by AngellusMortis** [comment]
Ah! I found it. Apparently, my searching skills are not that great. There is an attribute I missed for adding the correct typing to so the new logic will work on. I will fix it real fast.

**Comment by VederJay** [comment]
Instead of adding the local user (on unifi) to the Administrator group, I've added it to a more limited group which still has view + edit enabled but doesn't include the remote camera's. 
That seems a successful workaround until a fix is available.

**Comment by AngellusMortis** [comment]
I am just waiting for CI to pass for the fix. Then I will start the release process.

**Comment by VederJay** [comment]
Great! Let me know and I'll test it again.

**Comment by AngellusMortis** [comment]
Okay, just release 0.12-beta5. Let me know if it works.

**Comment by VederJay** [comment]
It works!
Thanks for all the effort!
