### ISSUE TITLE
[custom_components.unifiprotect] Unexpected error fetching unifiprotect data: 'lastRing'

### ISSUE THREAD

**Issue by panctronic** [briis/unifiprotect#54]
```
2020-05-20 13:12:46 ERROR (MainThread) [custom_components.unifiprotect] Unexpected error fetching unifiprotect data: 'lastRing'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/update_coordinator.py", line 136, in async_refresh
    self.data = await self._async_update_data()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/update_coordinator.py", line 124, in _async_update_data
    return await self.update_method()
  File "/home/homeassistant/.homeassistant/custom_components/unifiprotect/unifi_protect_server.py", line 72, in update
    await self._get_camera_list()
  File "/home/homeassistant/.homeassistant/custom_components/unifiprotect/unifi_protect_server.py", line 190, in _get_camera_list
    if camera["lastRing"] is None
KeyError: 'lastRing'
```

**Comment by briis** [comment]
What version of Unifi Protect are you using?

Please see this section in the README.md:

* This has been testet on a Cloud Key Gen2+ with Unifi Protect Controller version 1.13.3-beta.4 and higher. It will not work on a lower version than that.
* As of version 0.3.0, this Integration also supports the UDM Pro with UnifiOS, thanks to the work of @msvinth. You need the version of Unifi Protect that supports the Doorbell, or this Integration will fail.

**Comment by briis** [comment]
Saw your recent PR. I will look in to this. Thanks

**Comment by panctronic** [comment]
I'm stuck on Protect 1.12.5 due to my UDM Pro being on EA firmware. This component worked great until the doorbell PR (which I sync'd in this morning), but PR #55 gets things working again.
