### ISSUE TITLE
Error during setup - AuthenticationError

### ISSUE THREAD

**Issue by JakeHertenstein** [briis/unifiprotect#8]
First, thanks for your work!!
I was troubleshooting a problem with configuring the right username/password, and I noticed that there might be a problem here where it should be `response.status_code`, not `response.status`
https://github.com/briis/unifiprotect/blob/9376b25b5d94e5884c6b9bde4c8caae3249c3bd0/custom_components/unifiprotect/protectnvr.py#L74

Before I resolved the username/password issue, Hass returns this in the logs:
```
2020-01-05 12:04:40 ERROR (MainThread) [homeassistant.setup] Error during setup of component unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 176, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/unifiprotect/__init__.py", line 52, in setup
    nvrobject = nvr.protectRemote(host,port,username,password,use_ssl)
  File "/config/custom_components/unifiprotect/protectnvr.py", line 38, in __init__
    self._api_auth_bearer_token =  self._get_api_auth_bearer_token()
  File "/config/custom_components/unifiprotect/protectnvr.py", line 74, in _get_api_auth_bearer_token
    if response.status in (401, 403):
AttributeError: 'Response' object has no attribute 'status'
```

**Comment by briis** [comment]
Thanks for the feedback. I was just about to release a new version, but will fix this first.

**Comment by briis** [comment]
Release 0.0.8 is now out, and this has been fixed in that release. Thanks for reporting it.
